<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>In-Class Activity: Vibe Coding an Agriculture Management App</title>
<style>
body{font-family:Arial,sans-serif;line-height:1.6;margin:40px;color:#333}
h1,h2,h3{color:#2e7d32}
.container{max-width:1000px;margin:auto}
.section{margin-bottom:25px}
ul{margin-top:5px}
</style>
</head>
<body>
<div class="container">
<h1>In-Class Activity: Vibe Coding an Agriculture Management App (60 Minutes)</h1>
<p><strong>Course:</strong> Mobile App Development (Graduate Level)<br>
<strong>Technology:</strong> React Native + SQLite + AI Coding Tools<br>
<strong>Duration:</strong> 60 Minutes<br>
<strong>Format:</strong> Teams of 2–3 Students</p>

<h2>Activity Overview</h2>
<p>In this exercise, you will act as a mobile development team hired to create an MVP (Minimum Viable Product) for a farm management application. The client has provided only a list of possible features but has not specified detailed requirements. Your first task is to determine what the users need and then use vibe coding techniques (AI-assisted development) to rapidly prototype the application.</p>

<h2>Learning Objectives</h2>
<ul>
<li>Create requirements from a loosely defined problem.</li>
<li>Write effective prompts for AI-assisted software development.</li>
<li>Develop a React Native prototype using SQLite.</li>
<li>Design a mobile application with multiple interacting features.</li>
<li>Critically evaluate AI-generated code and design decisions.</li>
</ul>

<h2>Client Request</h2>
<p>The farm owner would like a mobile application that helps manage day-to-day farm operations.</p>

<h3>Mandatory Features</h3>
<ol>
<li><strong>Farm Map with Markers</strong><ul><li>Display the farm map</li><li>Allow users to place markers for fields, equipment, storage areas, etc.</li></ul></li>
<li><strong>Inventory of Supplies</strong><ul><li>Manage farm supplies and quantities</li><li>Data must be stored locally</li></ul></li>
</ol>

<h3>Additional Features (Choose at least 3)</h3>
<ul>
<li>Plant Rotation</li>
<li>Inventory Taken/Returned</li>
<li>Total Plants Planted</li>
<li>Money In/Out</li>
<li>Local Weather</li>
<li>Equipment Maintenance</li>
<li>Task Manager</li>
<li>Harvest Log</li>
<li>Spray and Fertilizer Records</li>
<li>Labor Tracking</li>
</ul>
<p><strong>Minimum Features Required: 5</strong></p>

<h2>Technical Constraints</h2>
<ul>
<li>Use React Native</li>
<li>Use SQLite for local storage</li>
<li>Be designed for offline use</li>
<li>Use AI tools (ChatGPT, Copilot, Claude, Cursor, Windsurf, etc.)</li>
</ul>

<h2>Activity Tasks (60 Minutes)</h2>
<h3>Part 1: Requirements Discovery (15 Minutes)</h3>
<p>As a team:</p>
<ul>
<li>Identify at least 3 stakeholders.</li>
<li>Create at least 5 user stories.</li>
<li>Select the 2 mandatory features and at least 3 additional features.</li>
</ul>

<h3>Part 2: Vibe Coding Design (10 Minutes)</h3>
<ul>
<li>Design at least 4 screens.</li>
<li>Create a simple SQLite schema for your application.</li>
</ul>

<h3>Part 3: AI-Assisted Prototype Development (25 Minutes)</h3>
<p>Use AI to generate code for:</p>
<ul>
<li>React Native navigation structure</li>
<li>SQLite database setup</li>
<li>Farm Map screen</li>
<li>Inventory screen</li>
<li>One additional feature screen</li>
</ul>

<h3>Part 4: Team Reflection (10 Minutes)</h3>
<ol>
<li>What prompts produced the best results?</li>
<li>What code generated by AI was useful?</li>
<li>What code required modification?</li>
<li>What requirements did your team define?</li>
<li>What are the strengths and weaknesses of vibe coding?</li>
</ol>

<h2>Example AI Prompts</h2>
<p><strong>Requirements Prompt:</strong><br>
You are a business analyst. Generate functional requirements and user stories for an agriculture management mobile application with farm mapping, inventory management, task tracking, and harvest logging.</p>

<p><strong>Database Prompt:</strong><br>
Design a SQLite database schema for a React Native farm management app containing inventory, map markers, tasks, and harvest tracking.</p>

<p><strong>React Native Prompt:</strong><br>
Generate React Native Expo code with SQLite and React Navigation for an agriculture management application containing Dashboard, Map, Inventory, and Task Manager screens.</p>

<h2>Deliverable</h2>
<ol>
<li>Selected features</li>
<li>Stakeholders</li>
<li>User stories</li>
<li>Simple screen design/wireframe</li>
<li>SQLite schema</li>
<li>Sample AI prompts used</li>
<li>Screenshots of generated prototype/code</li>
<li>Reflection (1–2 paragraphs)</li>
</ol>

<h2>Evaluation (100 Points)</h2>
<ul>
<li>Requirements Quality – 20</li>
<li>User Stories – 15</li>
<li>Feature Selection & Justification – 15</li>
<li>SQLite Design – 15</li>
<li>Prototype Design – 20</li>
<li>Effective Use of AI/Vibe Coding – 10</li>
<li>Reflection – 5</li>
</ul>

<h3>Challenge Bonus (+5)</h3>
<p>Create a convincing prompt that generates a complete React Native screen with SQLite CRUD functionality and explain why the prompt was effective.</p>
</div>
</body>
</html>